name: Lawtalk Continuos Integration

on:
  #Master Branch를 제외한 모든 Branch에서 동작
  #Push / Pull Request
  push:
    branchs:
      - '*'
      - '!master'
  pull_request:
    branchs:
      - '*'
      - '!master'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Code
      - name: Checkout
        uses: actions/checkout@v3

