name: Lawtalk Continuos Delivery

on:
  push:
    branchs:
      - '*'
      - '!master'
  pull_request:
    branchs:
      - '*'
      - '!master'

jobs:


# Checkout -> JDK Setup -> Grant Permisstion -> Build AAB -> Sign AAB ->
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout + JDK Setup
      - uses: actions/checkout@v3
      - name: SetUp JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      # Grant Permission + Build
      - name: Grant Permission Gradlew
        run: chmod +x gradlew
      - name: Build Gradle
        run: ./gradlew build --no-daemon

      # Build AAB
      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease
        #        AAB 생성 위치
        #        path: app/build/outputs/bundle/release/app-release.aab


      - name: alias check
        run: echo '${{ secrets.ALIAS }}'

      - name: base64 check
        run: echo '${{ secrets.SIGNING_KEY }}'


      - name: Generate Keystore file from Github Secrets
        run: |
          echo "$KEYSTORE" > ./keystore/keystore.b64
          base64 -d -i ./keystore/keystore.b64 > ./keystore/GitMaster.jks
        env:
          KEYSTORE: ${{ secrets.SIGNING_KEY }}



      # Sign AAB
      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ga0RGNYHvNM5d0SLGQfpQWAPGJ8=
          alias: key0
          keyStorePassword: 123456
          keyPassword: 123456
#          releaseDirectory: app/build/outputs/bundle/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: app/build/outputs/bundle/release/app-release.aab
#        env:
#          BUILD_TOOLS_VERSION: 30.0.2

#      - name: Upload AAB
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJson: ${{ SERVICE_ACCOUNT_JSON }}
#          packageName: ${{ PACKAGE_NAME }}
#          releaseFile: ${{ SIGNED_RELEASE_FILE }}
#          track: internal
#          inAppUpdatePriority: 2
#          userFraction: 0.33
#          whatsNewDirectory: distribution/whatsnew
#          mappingFile: app/build/outputs/mapping/release/mapping.txt
