name: Lawtalk Continuos Integration

on:
  push:
    branchs:
      - '*'
      - '!master'
  pull_request:
    branchs:
      - '*'
      - '!master'

jobs:
  #  Lint 검사
  lint-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html
  # Build
  build:
    needs: [lint-check]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: SetUp JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant Permission Gradlew
        run: chmod +x gradlew
      - name: Build Gradle
        run: ./gradlew build --no-daemon

  #  AVD 테스트
  avd-test:
    needs: [build]
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [30, 21, 17]
        target: [google_apis]
        arch: [x86]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: UnitTest
#        run: ./gradlew test

#      - name: Upload UnitTest Report
#      - uses: action/upload-artiface@v2
#        with:
#          name: unitTestReport.html
#          path: app/build/reports/tests/testDebugUnitTest/index.html

      - name: Run Android AVD Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: Galaxy Nexus
          script: ./gradlew androidTest
