name: Lawtalk Continuos Integration

on:
  #Master Branch를 제외한 모든 Branch에서 동작
  #Push / Pull Request
  push:
    branchs:
      - '*'
      - '!master'
  pull_request:
    branchs:
      - '*'
      - '!master'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: Run Android 11 Test
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 30
#          script: ./gradlew connectedCheck

      - name: Run Android 10 Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Run Android 9 Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew connectedCheck

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/
