name: Lawtalk Continuos Delivery

on:
  push:
  pull_request:
    branches-ignore:
      - 'master'
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
      - name: SetUp JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant Permission Gradlew
        run: chmod +x gradlew

      - name: Build Gradle
        run: ./gradlew build --no-daemon

  sign-aab:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease

      - name: Sign App AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: app/build/outputs/bundle/release/app-release.aab